// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_Image3;
lv_obj_t * uic_Screen3;
lv_obj_t * ui_Screen3;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Image3;

// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 795);
    lv_obj_set_height(ui_Container2, 473);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_image_create(ui_Screen3);
    lv_image_set_src(ui_Image3, &ui_img_11_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image3, -20);
    lv_obj_set_y(ui_Image3, 16);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_Screen3 = ui_Screen3;
    uic_Image3 = ui_Image3;

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    uic_Screen3 = NULL;
    ui_Screen3 = NULL;
    ui_Container2 = NULL;
    uic_Image3 = NULL;
    ui_Image3 = NULL;

}
