// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_Image6;
lv_obj_t * uic_Image5;
lv_obj_t * uic_Image4;
lv_obj_t * uic_Image1;
lv_obj_t * uic_Screen1;
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Chart1;
lv_obj_t * ui_Chart1_Xaxis;
lv_obj_t * ui_Chart1_Yaxis1;
lv_obj_t * ui_Chart1_Yaxis2;
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Spinbox1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Arc1;

// event funtions
void ui_event_Image4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Image5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Image6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_arc_increment(ui_Arc1, 10);
        _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, "Hello, World!");
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 597);
    lv_obj_set_height(ui_Container3, 298);
    lv_obj_set_x(ui_Container3, -4);
    lv_obj_set_y(ui_Container3, -53);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider1 = lv_slider_create(ui_Container3);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 50, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 194);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, 3);
    lv_obj_set_y(ui_Slider1, 131);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Chart1 = lv_chart_create(ui_Container3);
    lv_obj_set_width(ui_Chart1, 298);
    lv_obj_set_height(ui_Chart1, 163);
    lv_obj_set_x(ui_Chart1, -17);
    lv_obj_set_y(ui_Chart1, 2);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart1, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);

    ui_Chart1_Xaxis = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart1_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart1_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart1_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart1,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart1_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart1_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart1_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Xaxis, 2 >= 1 ? 2 : 1);
    ui_Chart1_Yaxis1 = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart1_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart1_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart1_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart1,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart1_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart1_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_Chart1_Yaxis2 = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart1_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart1_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart1_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart1,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart1_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart1_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart1, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_Switch1 = lv_switch_create(ui_Container3);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 59);
    lv_obj_set_y(ui_Switch1, 20);
    lv_obj_add_state(ui_Switch1, LV_STATE_CHECKED);       /// States

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0xFBFBF7), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch1, lv_color_hex(0xE27575), LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Container3);
    lv_image_set_src(ui_Image1, &ui_img_1_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Image1, 233);
    lv_obj_set_y(ui_Image1, 15);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Image1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Image1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_Image1, LV_IMAGE_ALIGN_TOP_LEFT);

    ui_Spinbox1 = lv_spinbox_create(ui_Screen1);
    lv_obj_set_width(ui_Spinbox1, 70);
    lv_obj_set_height(ui_Spinbox1, 42);
    lv_obj_set_x(ui_Spinbox1, -72);
    lv_obj_set_y(ui_Spinbox1, -160);
    lv_obj_set_align(ui_Spinbox1, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox1, 4, 2);
    lv_spinbox_set_range(ui_Spinbox1, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_Spinbox1, 1 - 1);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 41);
    lv_obj_set_y(ui_Label1, -163);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Hello HDU!");

    ui_Image4 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image4, &ui_img_switch_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -265);
    lv_obj_set_y(ui_Image4, 180);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image5, &ui_img_switch_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, -31);
    lv_obj_set_y(ui_Image5, 179);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image6, &ui_img_switch_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, 203);
    lv_obj_set_y(ui_Image6, 178);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc1, 150);
    lv_obj_set_height(ui_Arc1, 150);
    lv_obj_set_x(ui_Arc1, -299);
    lv_obj_set_y(ui_Arc1, -42);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);

    lv_obj_add_event_cb(ui_Image4, ui_event_Image4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image5, ui_event_Image5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image6, ui_event_Image6, LV_EVENT_ALL, NULL);
    uic_Screen1 = ui_Screen1;
    uic_Image1 = ui_Image1;
    uic_Image4 = ui_Image4;
    uic_Image5 = ui_Image5;
    uic_Image6 = ui_Image6;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    uic_Screen1 = NULL;
    ui_Screen1 = NULL;
    ui_Container3 = NULL;
    ui_Slider1 = NULL;
    ui_Chart1 = NULL;
    ui_Switch1 = NULL;
    uic_Image1 = NULL;
    ui_Image1 = NULL;
    ui_Spinbox1 = NULL;
    ui_Label1 = NULL;
    uic_Image4 = NULL;
    ui_Image4 = NULL;
    uic_Image5 = NULL;
    ui_Image5 = NULL;
    uic_Image6 = NULL;
    ui_Image6 = NULL;
    ui_Arc1 = NULL;

}
