// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart1_Xaxis;
extern lv_obj_t * ui_Chart1_Yaxis1;
extern lv_obj_t * ui_Chart1_Yaxis2;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Spinbox1;
extern lv_obj_t * ui_Label1;
extern void ui_event_Image4(lv_event_t * e);
extern lv_obj_t * ui_Image4;
extern void ui_event_Image5(lv_event_t * e);
extern lv_obj_t * ui_Image5;
extern void ui_event_Image6(lv_event_t * e);
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Arc1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen1;
extern lv_obj_t * uic_Image1;
extern lv_obj_t * uic_Image4;
extern lv_obj_t * uic_Image5;
extern lv_obj_t * uic_Image6;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

